<?php

namespace Database\Seeders;

use App\Models\Lead;
use App\Models\ApiKey;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class LeadSeeder extends Seeder
{
    /**
     * Seed leads from sample CSV data and create a default API key.
     */
    public function run(): void
    {
        // ─── Sample Leads (from docs/sample_lead_list.csv) ────────────
        $leads = [
            ['full_name' => 'Daniel Whitfield', 'job_title' => 'President', 'title_tier' => 'C-Level', 'corporate_email' => 'd.whitfield@brightharbor.com', 'email_status' => '✔ Valid email', 'company_name' => 'Bright Harbor Group', 'clean_root_domain' => 'brightharbor.com', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/danielwhitfield', 'company_linkedin_page' => 'https://www.linkedin.com/company/brightharbor', 'industry_classification' => 'Real Estate', 'employee_headcount' => 42, 'hq_location' => 'Lisbon, Lisbon, Portugal', 'country' => 'Portugal'],
            ['full_name' => 'Ana Carolina Pinto', 'job_title' => 'CEO & Co-Founder', 'title_tier' => 'C-Level', 'corporate_email' => 'ana.pinto@novatrail.io', 'email_status' => '✔ Valid email', 'company_name' => 'NovaTrail', 'clean_root_domain' => 'novatrail.io', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/anacarolinapinto', 'company_linkedin_page' => 'https://www.linkedin.com/company/novatrail', 'industry_classification' => 'Software', 'employee_headcount' => 18, 'hq_location' => 'Porto, Porto, Portugal', 'country' => 'Portugal'],
            ['full_name' => 'Victor Hugo Marques', 'job_title' => 'Co-Founder & Partner', 'title_tier' => 'C-Level', 'corporate_email' => 'victor.marques@luxuryfitco.pt', 'email_status' => '✔ Valid email', 'company_name' => 'Luxury Fit Co', 'clean_root_domain' => 'luxuryfitco.pt', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/victorhugomarques', 'company_linkedin_page' => 'https://www.linkedin.com/company/luxuryfitco', 'industry_classification' => 'Fitness & Wellness', 'employee_headcount' => 9, 'hq_location' => 'Lisbon, Lisbon, Portugal', 'country' => 'Portugal'],
            ['full_name' => 'Celia Lencastre', 'job_title' => 'Founder', 'title_tier' => 'C-Level', 'corporate_email' => 'celia@lencastreestates.pt', 'email_status' => '✔ Valid email', 'company_name' => 'Lencastre Real Estate', 'clean_root_domain' => 'lencastreestates.pt', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/celialencastre', 'company_linkedin_page' => 'https://www.linkedin.com/company/lencastreestates', 'industry_classification' => 'Real Estate', 'employee_headcount' => 27, 'hq_location' => 'Cascais, Lisbon, Portugal', 'country' => 'Portugal'],
            ['full_name' => 'Rui Pedro Bairrada', 'job_title' => 'Founder & Partner', 'title_tier' => 'C-Level', 'corporate_email' => 'rui.bairrada@doutorfinancas.pt', 'email_status' => '✔ Valid email', 'company_name' => 'Doutor Financas', 'clean_root_domain' => 'doutorfinancas.pt', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/ruipedrobairrada', 'company_linkedin_page' => 'https://www.linkedin.com/company/doutorfinancas', 'industry_classification' => 'Financial Services', 'employee_headcount' => 61, 'hq_location' => 'Lisbon, Lisbon, Portugal', 'country' => 'Portugal'],
            ['full_name' => 'Jamal Reimer', 'job_title' => 'Founder & CEO', 'title_tier' => 'C-Level', 'corporate_email' => 'jamal@whyzer.ai', 'email_status' => '✔ Valid email', 'company_name' => 'Whyzer', 'clean_root_domain' => 'whyzer.ai', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/jamalreimer', 'company_linkedin_page' => 'https://www.linkedin.com/company/whyzer', 'industry_classification' => 'Artificial Intelligence', 'employee_headcount' => 14, 'hq_location' => 'Vienna, Vienna, Austria', 'country' => 'Austria'],
            ['full_name' => 'Sofia De Castro Fernandes', 'job_title' => 'Founder & CEO', 'title_tier' => 'C-Level', 'corporate_email' => 'sofia@sofiacastrofernandes.pt', 'email_status' => '✔ Valid email', 'company_name' => '3s Nove', 'clean_root_domain' => 'sofiacastrofernandes.pt', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/sofiadecastrofernandes', 'company_linkedin_page' => 'https://www.linkedin.com/company/3snove', 'industry_classification' => 'Fashion & Apparel', 'employee_headcount' => 8, 'hq_location' => 'Porto, Porto, Portugal', 'country' => 'Portugal'],
            ['full_name' => 'Samy Thuillier', 'job_title' => 'Co-Founder', 'title_tier' => 'C-Level', 'corporate_email' => 'samy@shiia.io', 'email_status' => '✔ Valid email', 'company_name' => 'Shiia', 'clean_root_domain' => 'shiia.io', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/samythuillier', 'company_linkedin_page' => 'https://www.linkedin.com/company/shiia', 'industry_classification' => 'Consumer Goods', 'employee_headcount' => 6, 'hq_location' => 'Vienna, Vienna, Austria', 'country' => 'Austria'],
            ['full_name' => 'Max Faust', 'job_title' => 'Co-Founder', 'title_tier' => 'C-Level', 'corporate_email' => 'max@innriches.co', 'email_status' => '✔ Valid email', 'company_name' => 'Venture Studio Family', 'clean_root_domain' => 'innriches.co', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/maxfaust', 'company_linkedin_page' => 'https://www.linkedin.com/company/innriches', 'industry_classification' => 'Venture Capital', 'employee_headcount' => 11, 'hq_location' => 'Vienna, Vienna, Austria', 'country' => 'Austria'],
            ['full_name' => 'Paddy Cosgrave', 'job_title' => 'Founder', 'title_tier' => 'C-Level', 'corporate_email' => 'paddy@websummit.com', 'email_status' => '✔ Valid email', 'company_name' => 'Web Summit', 'clean_root_domain' => 'websummit.com', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/paddycosgrave', 'company_linkedin_page' => 'https://www.linkedin.com/company/websummit', 'industry_classification' => 'Events', 'employee_headcount' => 210, 'hq_location' => 'Lisbon, Lisbon, Portugal', 'country' => 'Portugal'],
            ['full_name' => 'Pedro Branco', 'job_title' => 'Founder & CEO', 'title_tier' => 'C-Level', 'corporate_email' => 'pb@pedrobranco.net', 'email_status' => '✔ Valid email', 'company_name' => 'Pedro Branco & Partners', 'clean_root_domain' => 'pedrobranco.net', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/pedrobranco', 'company_linkedin_page' => 'https://www.linkedin.com/company/pedrobrancopartners', 'industry_classification' => 'Legal Services', 'employee_headcount' => 23, 'hq_location' => 'Lisbon, Lisbon, Portugal', 'country' => 'Portugal'],
            ['full_name' => 'Gonçalo Sequeira', 'job_title' => 'Founder & CEO', 'title_tier' => 'C-Level', 'corporate_email' => 'goncalo@hire.me', 'email_status' => '✔ Valid email', 'company_name' => 'Hire', 'clean_root_domain' => 'hire.me', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/goncalosequeira', 'company_linkedin_page' => 'https://www.linkedin.com/company/hireme', 'industry_classification' => 'Human Resources', 'employee_headcount' => 15, 'hq_location' => 'Lisbon, Lisbon, Portugal', 'country' => 'Portugal'],
            ['full_name' => 'Barak Bravit', 'job_title' => 'CEO', 'title_tier' => 'C-Level', 'corporate_email' => 'barak@blue-monkeys.com', 'email_status' => '✔ Valid email', 'company_name' => 'Blue Monkeys Productions', 'clean_root_domain' => 'blue-monkeys.com', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/barakbravit', 'company_linkedin_page' => 'https://www.linkedin.com/company/bluemonkeys', 'industry_classification' => 'Media Production', 'employee_headcount' => 34, 'hq_location' => 'Vienna, Vienna, Austria', 'country' => 'Austria'],
            ['full_name' => 'Tim Vieira', 'job_title' => 'CEO and Founder', 'title_tier' => 'C-Level', 'corporate_email' => 'tim@brave-generation.academy', 'email_status' => '✔ Valid email', 'company_name' => 'Brave Generation Academy', 'clean_root_domain' => 'brave-generation.academy', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/timvieira', 'company_linkedin_page' => 'https://www.linkedin.com/company/bravegenerationacademy', 'industry_classification' => 'Education', 'employee_headcount' => 47, 'hq_location' => 'Porto, Porto, Portugal', 'country' => 'Portugal'],
            ['full_name' => 'Nuno Fraga', 'job_title' => 'Owner', 'title_tier' => 'C-Level', 'corporate_email' => 'nuno@hire-trust.net', 'email_status' => '✔ Valid email', 'company_name' => 'Harmonia Publishing', 'clean_root_domain' => 'hire-trust.net', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/nunofraga', 'company_linkedin_page' => 'https://www.linkedin.com/company/harmoniapublishing', 'industry_classification' => 'Publishing', 'employee_headcount' => 12, 'hq_location' => 'Coimbra, Coimbra, Portugal', 'country' => 'Portugal'],
            ['full_name' => 'Norah Casey', 'job_title' => 'Founder & Chief Executive', 'title_tier' => 'C-Level', 'corporate_email' => 'norah@harmonia.ie', 'email_status' => '✔ Valid email', 'company_name' => 'Harmonia Group', 'clean_root_domain' => 'harmonia.ie', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/norahcasey', 'company_linkedin_page' => 'https://www.linkedin.com/company/harmoniagroup', 'industry_classification' => 'Media', 'employee_headcount' => 29, 'hq_location' => 'Dublin, Dublin, Ireland', 'country' => 'Ireland'],
            ['full_name' => 'Joao Figueiredo', 'job_title' => 'CEO | Carmo Form', 'title_tier' => 'C-Level', 'corporate_email' => 'joao@carmoform.com', 'email_status' => '✔ Valid email', 'company_name' => 'CarmoForm', 'clean_root_domain' => 'carmoform.com', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/joaofigueiredo', 'company_linkedin_page' => 'https://www.linkedin.com/company/carmoform', 'industry_classification' => 'Manufacturing', 'employee_headcount' => 55, 'hq_location' => 'Aveiro, Aveiro, Portugal', 'country' => 'Portugal'],
            ['full_name' => 'Mark Shortall', 'job_title' => 'Founder & Managing Director', 'title_tier' => 'Director-Level', 'corporate_email' => 'mark@pedorwork.io', 'email_status' => '✔ Valid email', 'company_name' => 'CEO/DXM - Precision Search', 'clean_root_domain' => 'pedorwork.io', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/markshortall', 'company_linkedin_page' => 'https://www.linkedin.com/company/precisionsearch', 'industry_classification' => 'Staffing & Recruiting', 'employee_headcount' => 19, 'hq_location' => 'Cork, Cork, Ireland', 'country' => 'Ireland'],
            ['full_name' => 'Mariana Silva', 'job_title' => 'CEO & Founder', 'title_tier' => 'C-Level', 'corporate_email' => 'mariana@rework.io', 'email_status' => '✔ Valid email', 'company_name' => 'Rework', 'clean_root_domain' => 'rework.io', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/marianasilva', 'company_linkedin_page' => 'https://www.linkedin.com/company/rework', 'industry_classification' => 'Software', 'employee_headcount' => 21, 'hq_location' => 'Lisbon, Lisbon, Portugal', 'country' => 'Portugal'],
            ['full_name' => 'Adrian Cummins', 'job_title' => 'Chief Executive Officer', 'title_tier' => 'C-Level', 'corporate_email' => 'adrian@rai.ie', 'email_status' => '✔ Valid email', 'company_name' => 'Restaurants Association of Ireland', 'clean_root_domain' => 'rai.ie', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/adriancummins', 'company_linkedin_page' => 'https://www.linkedin.com/company/rai', 'industry_classification' => 'Hospitality', 'employee_headcount' => 16, 'hq_location' => 'Dublin, Dublin, Ireland', 'country' => 'Ireland'],
            ['full_name' => 'Luis Madureira', 'job_title' => 'CEO | Managing Partner', 'title_tier' => 'C-Level', 'corporate_email' => 'luis@uberbrands.consulting', 'email_status' => '✔ Valid email', 'company_name' => 'UberBrands', 'clean_root_domain' => 'uberbrands.consulting', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/luismadureira', 'company_linkedin_page' => 'https://www.linkedin.com/company/uberbrands', 'industry_classification' => 'Consulting', 'employee_headcount' => 13, 'hq_location' => 'Lisbon, Lisbon, Portugal', 'country' => 'Portugal'],
            ['full_name' => 'Tiago Dias', 'job_title' => 'Founder, Product & CEO', 'title_tier' => 'C-Level', 'corporate_email' => 'tiago@tudobemescrito.pt', 'email_status' => '✔ Valid email', 'company_name' => 'Tudo Bem Escrito', 'clean_root_domain' => 'tudobemescrito.pt', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/tiagodias', 'company_linkedin_page' => 'https://www.linkedin.com/company/tudobemescrito', 'industry_classification' => 'Content & Writing', 'employee_headcount' => 7, 'hq_location' => 'Braga, Braga, Portugal', 'country' => 'Portugal'],
            ['full_name' => 'Martim Martins', 'job_title' => 'Founder', 'title_tier' => 'C-Level', 'corporate_email' => 'martim@clarity.ai', 'email_status' => '✔ Valid email', 'company_name' => 'Clarity AI', 'clean_root_domain' => 'clarity.ai', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/martimmartins', 'company_linkedin_page' => 'https://www.linkedin.com/company/clarityai', 'industry_classification' => 'Data & Analytics', 'employee_headcount' => 88, 'hq_location' => 'Madrid, Madrid, Spain', 'country' => 'Spain'],
            ['full_name' => 'Joana Paredes Alves', 'job_title' => 'CEO, Corporates & Government', 'title_tier' => 'C-Level', 'corporate_email' => 'joana@message.pt', 'email_status' => '✔ Valid email', 'company_name' => 'MESSAGE', 'clean_root_domain' => 'message.pt', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/joanaparedesalves', 'company_linkedin_page' => 'https://www.linkedin.com/company/message', 'industry_classification' => 'Public Relations', 'employee_headcount' => 24, 'hq_location' => 'Lisbon, Lisbon, Portugal', 'country' => 'Portugal'],
            ['full_name' => 'Filipe Mendes', 'job_title' => 'CEO & Founder', 'title_tier' => 'C-Level', 'corporate_email' => 'filipe@thegreenplan.io', 'email_status' => '✔ Valid email', 'company_name' => 'The Green Plan', 'clean_root_domain' => 'thegreenplan.io', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/filipemendes', 'company_linkedin_page' => 'https://www.linkedin.com/company/thegreenplan', 'industry_classification' => 'Sustainability', 'employee_headcount' => 10, 'hq_location' => 'Porto, Porto, Portugal', 'country' => 'Portugal'],
            ['full_name' => 'Neil Mccabe', 'job_title' => 'CEO & Founder', 'title_tier' => 'C-Level', 'corporate_email' => 'neil@cybersiscorp.io', 'email_status' => '✔ Valid email', 'company_name' => 'CYBERSISC - Cybersecurity Academy', 'clean_root_domain' => 'cybersiscorp.io', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/neilmccabe', 'company_linkedin_page' => 'https://www.linkedin.com/company/cybersisc', 'industry_classification' => 'Cybersecurity', 'employee_headcount' => 31, 'hq_location' => 'Dublin, Dublin, Ireland', 'country' => 'Ireland'],
            ['full_name' => 'Sergio S. Ferreira', 'job_title' => 'CEO & Founder', 'title_tier' => 'C-Level', 'corporate_email' => 'sergio@winning.io', 'email_status' => '✔ Valid email', 'company_name' => 'Winning', 'clean_root_domain' => 'winning.io', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/sergiosferreira', 'company_linkedin_page' => 'https://www.linkedin.com/company/winning', 'industry_classification' => 'Sports Technology', 'employee_headcount' => 17, 'hq_location' => 'Lisbon, Lisbon, Portugal', 'country' => 'Portugal'],
            ['full_name' => 'Carlos Hernandez Jeronimo', 'job_title' => 'Chief Executive Officer', 'title_tier' => 'C-Level', 'corporate_email' => 'carlos@karaconnect.com', 'email_status' => '✔ Valid email', 'company_name' => 'Kara Connect', 'clean_root_domain' => 'karaconnect.com', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/carloshernandezjeronimo', 'company_linkedin_page' => 'https://www.linkedin.com/company/karaconnect', 'industry_classification' => 'Healthcare Technology', 'employee_headcount' => 20, 'hq_location' => 'Reykjavik, Capital Region, Iceland', 'country' => 'Iceland'],
            ['full_name' => 'Tobba Vigfusdottir', 'job_title' => 'Chief Executive Officer', 'title_tier' => 'C-Level', 'corporate_email' => 'tobba@karaconnect.com', 'email_status' => '✔ Valid email', 'company_name' => 'Kara Connect', 'clean_root_domain' => 'karaconnect.com', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/tobbavigfusdottir', 'company_linkedin_page' => 'https://www.linkedin.com/company/karaconnect', 'industry_classification' => 'Healthcare Technology', 'employee_headcount' => 20, 'hq_location' => 'Reykjavik, Capital Region, Iceland', 'country' => 'Iceland'],
            ['full_name' => 'Pritesh Tiwari', 'job_title' => 'Founder & Chief Data Scientist', 'title_tier' => 'C-Level', 'corporate_email' => 'pritesh@datasciencewizards.ai', 'email_status' => '✔ Valid email', 'company_name' => 'DSW | Data Science Wizards', 'clean_root_domain' => 'datasciencewizards.ai', 'website_status' => '✔ HTTP 200 OK', 'executive_linkedin_url' => 'https://www.linkedin.com/in/priteshtiwari', 'company_linkedin_page' => 'https://www.linkedin.com/company/datasciencewizards', 'industry_classification' => 'Data Science', 'employee_headcount' => 25, 'hq_location' => 'Bangalore, Karnataka, India', 'country' => 'India'],
        ];

        foreach ($leads as $lead) {
            Lead::updateOrCreate(
                ['corporate_email' => $lead['corporate_email']],
                array_merge($lead, [
                    'ingestion_channel' => 'csv_import',
                    'status' => 'new',
                ])
            );
        }

        $this->command->info('Seeded ' . count($leads) . ' sample leads.');

        // ─── Default API Key ──────────────────────────────────
        $plainKey = 'jb_live_' . Str::random(32);
        ApiKey::updateOrCreate(
            ['name' => 'default-dev-key'],
            [
                'key'                   => hash('sha256', $plainKey),
                'plain_text_prefix'     => substr($plainKey, 0, 8),
                'rate_limit_per_minute' => 0, // unlimited for dev
                'is_active'             => true,
            ]
        );

        $this->command->info("Default API key created: {$plainKey}");
        $this->command->info('⚠️  Save this key — it cannot be retrieved after this.');
    }
}
